spring.application.name=jaz-s32945-nbp

spring.datasource.url=jdbc:mysql://localhost:3306/nbp_calculator?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none